(function(){
  "use strict";
  var source=window.BUILDING_OPERATIONS_DATA;if(!source)return;
  var original=source.reports.map(function(item){return Object.assign({},item);});
  var state={view:"building",type:"all",status:"open",selectedId:source.reports[0].id,reports:original.map(function(item){return Object.assign({},item);}),sequence:300};
  function escapeHtml(value){return String(value).replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
  function view(){return source.views.find(function(item){return item.id===state.view;})||source.views[0];}
  function visible(){return state.reports.filter(function(item){return item.view===state.view&&(state.type==="all"||item.type===state.type)&&(state.status==="all"||item.status!=="Resolved");});}
  function selected(){var list=visible();return state.reports.find(function(item){return item.id===state.selectedId;})||list[0]||state.reports.find(function(item){return item.view===state.view;})||state.reports[0];}
  function setup(){
    document.querySelector("[data-view-controls]").innerHTML=source.views.map(function(item){return'<button type="button" data-view="'+item.id+'" aria-pressed="'+String(item.id===state.view)+'">'+escapeHtml(item.label)+"</button>";}).join("");
    document.querySelector("[data-type-filter]").insertAdjacentHTML("beforeend",source.reportTypes.map(function(type){return'<option value="'+type+'">'+type+"</option>";}).join(""));
    document.querySelector("[data-new-type]").innerHTML=source.reportTypes.map(function(type){return'<option value="'+type+'">'+type+"</option>";}).join("");
    bind();renderArchitecture();render();
  }
  function bind(){
    document.querySelectorAll("[data-view]").forEach(function(button){button.addEventListener("click",function(){state.view=button.getAttribute("data-view");state.selectedId="";document.querySelectorAll("[data-view]").forEach(function(item){item.setAttribute("aria-pressed",String(item===button));});render();});});
    document.querySelector("[data-type-filter]").addEventListener("change",function(event){state.type=event.target.value;state.selectedId="";render();});
    document.querySelector("[data-status-filter]").addEventListener("change",function(event){state.status=event.target.value;state.selectedId="";render();});
    document.querySelector("[data-reset]").addEventListener("click",function(){state.reports=original.map(function(item){return Object.assign({},item);});state.view="building";state.type="all";state.status="open";state.selectedId=state.reports[0].id;document.querySelector("[data-type-filter]").value="all";document.querySelector("[data-status-filter]").value="open";document.querySelectorAll("[data-view]").forEach(function(item){item.setAttribute("aria-pressed",String(item.getAttribute("data-view")==="building"));});document.querySelector("[data-action-message]").textContent="Scenario reset.";render();});
    document.querySelectorAll("[data-action]").forEach(function(button){button.addEventListener("click",function(){updateStatus(button.getAttribute("data-action"));});});
    document.querySelector("[data-submit-report]").addEventListener("click",createReport);
  }
  function render(){var currentView=view();var list=visible();if(!state.selectedId&&list[0])state.selectedId=list[0].id;document.querySelector("[data-map-title]").textContent=currentView.title;document.querySelector("[data-map-subtitle]").textContent=currentView.subtitle;document.querySelector("[data-kpi-view]").textContent=currentView.label;renderZones(currentView);renderKpis();renderMarkers(list);renderQueue(list);renderDetail();renderReportZones(currentView);}
  function renderZones(currentView){document.querySelector("[data-zones]").innerHTML=currentView.zones.map(function(zone){return"<span>"+escapeHtml(zone)+"</span>";}).join("");}
  function renderKpis(){var scoped=state.reports.filter(function(item){return item.view===state.view;});document.querySelector("[data-kpi-active]").textContent=scoped.filter(function(item){return item.status!=="Resolved";}).length;document.querySelector("[data-kpi-priority]").textContent=scoped.filter(function(item){return item.status!=="Resolved"&&(item.severity==="critical"||item.severity==="high");}).length;document.querySelector("[data-kpi-work]").textContent=scoped.filter(function(item){return item.status==="Work requested";}).length;}
  function renderMarkers(list){var container=document.querySelector("[data-markers]");container.innerHTML=list.map(function(item){return'<button type="button" class="report-marker severity-'+item.severity+'" style="left:'+item.x+'%;top:'+item.y+'%" data-select="'+item.id+'" aria-label="'+escapeHtml(item.id+", "+item.summary)+'" aria-current="'+String(item.id===state.selectedId)+'"></button>';}).join("");bindSelections(container);}
  function renderQueue(list){document.querySelector("[data-queue-count]").textContent=list.length+" shown";var container=document.querySelector("[data-queue]");container.innerHTML=list.length?list.map(function(item){return'<button type="button" class="queue-item" data-select="'+item.id+'" aria-current="'+String(item.id===state.selectedId)+'"><i class="severity-'+item.severity+'"></i><div><strong>'+escapeHtml(item.summary)+'</strong><small>'+escapeHtml(item.zone+" · "+item.asset+" · "+item.status)+'</small></div><b>'+escapeHtml(item.age)+'</b></button>';}).join(""):'<div class="empty-state">No reports match the current filters.</div>';bindSelections(container);}
  function bindSelections(container){container.querySelectorAll("[data-select]").forEach(function(button){button.addEventListener("click",function(){state.selectedId=button.getAttribute("data-select");document.querySelector("[data-action-message]").textContent="";render();});});}
  function renderDetail(){var item=selected();if(!item)return;state.selectedId=item.id;document.querySelector("[data-detail-id]").textContent=item.id+" · "+item.age;document.querySelector("[data-detail-summary]").textContent=item.summary;document.querySelector("[data-detail-severity]").textContent=item.severity;document.querySelector("[data-detail-severity]").className="severity-"+item.severity;document.querySelector("[data-detail-location]").textContent=item.zone+" / "+item.asset;document.querySelector("[data-detail-type]").textContent=item.type;document.querySelector("[data-detail-status]").textContent=item.status;document.querySelector("[data-detail-owner]").textContent=item.owner;document.querySelector("[data-detail-text]").textContent=item.detail;}
  function updateStatus(action){var item=selected();if(!item)return;var next={acknowledge:"Acknowledged",work:"Work requested",resolve:"Resolved"}[action];item.status=next;document.querySelector("[data-action-message]").textContent=item.id+" updated to "+next+" in this synthetic session.";render();}
  function renderReportZones(currentView){var select=document.querySelector("[data-new-zone]");var previous=select.value;select.innerHTML=currentView.zones.map(function(zone){return'<option value="'+escapeHtml(zone)+'">'+escapeHtml(zone)+"</option>";}).join("");if(currentView.zones.indexOf(previous)>-1)select.value=previous;}
  function createReport(){var summary=document.querySelector("[data-new-summary]").value.trim()||"Modeled observation requires review";var severity=document.querySelector("[data-new-severity]").value;state.sequence+=1;var item={id:(state.view==="building"?"OPS-":"MCH-")+state.sequence,view:state.view,zone:document.querySelector("[data-new-zone]").value,asset:state.view==="building"?"Synthetic location":"Synthetic asset",type:document.querySelector("[data-new-type]").value,severity:severity,status:"Open",x:26+(state.sequence%5)*12,y:24+(state.sequence%4)*15,age:"just now",owner:severity==="critical"?"Operations / EHS":"Triage queue",summary:summary,detail:"User-created synthetic record. A real implementation would preserve evidence, route ownership, validate permissions, and retain an audit history."};state.reports.unshift(item);state.selectedId=item.id;state.type="all";state.status="open";document.querySelector("[data-type-filter]").value="all";document.querySelector("[data-status-filter]").value="open";document.querySelector("[data-action-message]").textContent=item.id+" added to the synthetic queue.";render();}
  function renderArchitecture(){document.querySelector("[data-architecture]").innerHTML=source.architecture.map(function(node,index){return'<div class="architecture-node"><span>0'+(index+1)+'</span><strong>'+escapeHtml(node.name)+'</strong><small>'+escapeHtml(node.detail)+'</small></div>'+(index<source.architecture.length-1?'<b class="architecture-arrow" aria-hidden="true">→</b>':"");}).join("");}
  setup();
})();
