(function(){
  "use strict";
  var source=window.DIGITAL_KANBAN_DATA;if(!source)return;
  var initial=source.initialRequests.map(function(item){return Object.assign({},item);});
  var state={stockPointId:source.stockPoints[0].id,scanned:false,selected:[],requests:initial.map(function(item){return Object.assign({},item);}),history:[{time:"08:18",title:"Request created",detail:"Liner bags · North Janitorial Point"},{time:"08:42",title:"Request created",detail:"Disposable utensils · East Break Room"}],blocked:0,completed:0,sequence:7000};
  function escapeHtml(value){return String(value).replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
  function stockPoint(){return source.stockPoints.find(function(item){return item.id===state.stockPointId;})||source.stockPoints[0];}
  function openRequests(){return state.requests.filter(function(item){return item.status==="Requested";});}
  function openKey(item){return item.stockPointItemId+"|"+item.requestType;}
  function itemKey(item){return item.id+"|"+item.requestType;}
  function isOpen(item){var key=itemKey(item);return openRequests().some(function(request){return openKey(request)===key;});}
  function setup(){var route=document.querySelector("[data-route]");route.innerHTML=source.stockPoints.map(function(item){return'<option value="'+item.id+'">'+escapeHtml(item.name+" · "+(item.mode==="direct"?"Direct item":"Storefront"))+"</option>";}).join("");route.addEventListener("change",function(){state.stockPointId=route.value;state.scanned=false;state.selected=[];render();});document.querySelector("[data-scan]").addEventListener("click",scan);document.querySelector("[data-phone-scan]").addEventListener("click",scan);document.querySelector("[data-submit]").addEventListener("click",submit);document.querySelector("[data-reset]").addEventListener("click",reset);renderArchitecture();render();}
  function scan(){state.scanned=true;state.selected=[];var point=stockPoint();if(point.mode==="direct"&&!isOpen(point.items[0]))state.selected=[point.items[0].id];document.querySelector("[data-notice]").textContent="Synthetic QR route resolved to "+point.name+".";state.history.unshift({time:"now",title:"QR route resolved",detail:point.name+" · "+point.mode});render();}
  function render(){var point=stockPoint();document.querySelector("[data-route-mode]").textContent=point.mode==="direct"?"DIRECT ITEM":"MULTI-ITEM STOREFRONT";document.querySelector("[data-route-key]").textContent="route / "+point.route;document.querySelector("[data-kpi-open]").textContent=openRequests().length;document.querySelector("[data-kpi-blocked]").textContent=state.blocked;document.querySelector("[data-kpi-complete]").textContent=state.completed;document.querySelector("[data-kpi-location]").textContent=state.scanned?point.name:"Awaiting scan";document.querySelector("[data-kpi-practical]").textContent=state.scanned?point.location:"Choose a route and simulate a QR scan";document.querySelector("[data-stockpoint-name]").textContent=state.scanned?point.name:"Scan a QR route";document.querySelector("[data-stockpoint-location]").textContent=state.scanned?point.location:"Select a synthetic route above to begin.";document.querySelector("[data-route-badge]").textContent=state.scanned?(point.mode==="direct"?"DIRECT":"STOREFRONT"):"WAITING";document.querySelector("[data-phone-scan]").hidden=state.scanned;renderItems(point);renderSelection(point);renderRequests();renderHistory();}
  function renderItems(point){var container=document.querySelector("[data-items]");if(!state.scanned){container.innerHTML='<div class="empty-state">The requester sees only the stock point resolved by the scanned route.</div>';return;}container.innerHTML=point.items.map(function(item){var blocked=isOpen(item);var selected=state.selected.indexOf(item.id)>-1;return'<button type="button" class="item-card" data-item="'+item.id+'" data-blocked="'+String(blocked)+'" aria-pressed="'+String(selected)+'"><span>'+escapeHtml(item.id)+'</span><strong>'+escapeHtml(item.name)+'</strong><small>'+escapeHtml(item.trigger+" · Standard "+item.standardQty+" "+item.unit)+'</small><b>'+(blocked?"Already requested":selected?"Selected":"Select for replenishment")+'</b></button>';}).join("");container.querySelectorAll("[data-item]").forEach(function(button){button.addEventListener("click",function(){toggleItem(button.getAttribute("data-item"));});});}
  function toggleItem(id){var point=stockPoint();var item=point.items.find(function(candidate){return candidate.id===id;});if(!item)return;if(isOpen(item)){state.blocked+=1;document.querySelector("[data-notice]").textContent="Duplicate blocked: an open "+item.requestType.toLowerCase()+" request already exists for "+item.name+".";render();return;}if(point.mode==="direct"){state.selected=[id];}else{var index=state.selected.indexOf(id);if(index>-1)state.selected.splice(index,1);else state.selected.push(id);}render();}
  function renderSelection(point){var allowed=state.scanned&&state.selected.length>0;document.querySelector("[data-submit]").disabled=!allowed;document.querySelector("[data-selection-summary]").textContent=!state.scanned?"Scan a route to identify a controlled stock point.":state.selected.length?state.selected.length+" item"+(state.selected.length===1?"":"s")+" selected for "+point.name+".":"No eligible items selected. Open items show their existing request state.";}
  function submit(){var point=stockPoint();if(!state.scanned||!state.selected.length)return;var created=0;var blocked=0;state.selected.slice().forEach(function(id){var item=point.items.find(function(candidate){return candidate.id===id;});if(!item)return;if(isOpen(item)){blocked+=1;state.blocked+=1;return;}state.sequence+=1;state.requests.unshift({id:"REQ-"+state.sequence,stockPointId:point.id,stockPointItemId:item.id,requestType:item.requestType,itemName:item.name,stockPointName:point.name,location:point.location,quantity:item.standardQty+" "+item.unit,status:"Requested",requested:"now"});state.history.unshift({time:"now",title:"Request created",detail:item.name+" · "+point.name});created+=1;});state.selected=[];document.querySelector("[data-notice]").textContent=created+" request"+(created===1?"":"s")+" created"+(blocked?"; "+blocked+" duplicate blocked":"")+". The restocker queue is updated.";render();if(created&&document.querySelector("#kanban-device").getAttribute("data-device-mode")==="phone"){var tablet=document.querySelector('[data-preview-mode="tablet"]');if(tablet)tablet.click();}}
  function renderRequests(){var list=openRequests();document.querySelector("[data-open-count]").textContent=list.length+" open";document.querySelector("[data-open-requests]").innerHTML=list.length?list.map(function(item){return'<article class="request-item"><span>'+escapeHtml(item.id+" · REQUESTED "+item.requested)+'</span><strong>'+escapeHtml(item.itemName+" · "+item.quantity)+'</strong><small>'+escapeHtml(item.stockPointName+" · "+item.location)+'</small><button type="button" data-complete="'+item.id+'">Mark refilled</button></article>';}).join(""):'<div class="empty-state">No open replenishment requests.</div>';document.querySelectorAll("[data-complete]").forEach(function(button){button.addEventListener("click",function(){complete(button.getAttribute("data-complete"));});});}
  function complete(id){var request=state.requests.find(function(item){return item.id===id;});if(!request)return;request.status="Complete";state.completed+=1;state.history.unshift({time:"now",title:"Marked refilled",detail:request.itemName+" · "+request.stockPointName});document.querySelector("[data-notice]").textContent=request.id+" completed. Its duplicate-control key is now available for the next physical signal.";render();}
  function renderHistory(){document.querySelector("[data-history]").innerHTML=state.history.slice(0,8).map(function(item){return'<li><time>'+escapeHtml(item.time)+'</time><strong>'+escapeHtml(item.title)+'</strong><small>'+escapeHtml(item.detail)+'</small></li>';}).join("");}
  function reset(){state.scanned=false;state.selected=[];state.requests=initial.map(function(item){return Object.assign({},item);});state.history=[{time:"08:18",title:"Request created",detail:"Liner bags · North Janitorial Point"},{time:"08:42",title:"Request created",detail:"Disposable utensils · East Break Room"}];state.blocked=0;state.completed=0;document.querySelector("[data-notice]").textContent="Scenario reset.";render();}
  function renderArchitecture(){document.querySelector("[data-architecture]").innerHTML=source.architecture.map(function(node,index){return'<div class="architecture-node"><span>0'+(index+1)+'</span><strong>'+escapeHtml(node.name)+'</strong><small>'+escapeHtml(node.detail)+'</small></div>'+(index<source.architecture.length-1?'<b class="architecture-arrow" aria-hidden="true">→</b>':"");}).join("");}
  setup();
})();
